version: '3.7'

services:
  db:
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - "5432"
    expose:
      - "5432"
    volumes:
      - bookstore_data:/var/lib/postgresql/data/
    networks:
      django_network:

  web:
    restart: always
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
#    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
    networks:
      django_network:

volumes:
  bookstore_data:
    driver: local
networks:
  django_network:
    driver: bridge
